// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("FiveChecks")]
[assembly: AssemblyDescription("Shows compliance notifications to the user.")]
[assembly: AssemblyProduct("FiveChecks")]
[assembly: AssemblyCopyright("Copyright © github.trondr 2020")]
[assembly: AssemblyCompany("FiveChecks")]
[assembly: AssemblyVersion("1.0.20140.46")]
[assembly: AssemblyFileVersion("1.0.20140.46")]
[assembly: ComVisible(false)]
[assembly: Guid("8B2765D7-A756-45AA-B7BD-4FB98F9F51F4")]
[assembly: InternalsVisibleTo("FiveChecks.Tests")]
[assembly: NeutralResourcesLanguage("en-US")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FiveChecks";
        internal const System.String AssemblyDescription = "Shows compliance notifications to the user.";
        internal const System.String AssemblyProduct = "FiveChecks";
        internal const System.String AssemblyCopyright = "Copyright © github.trondr 2020";
        internal const System.String AssemblyCompany = "FiveChecks";
        internal const System.String AssemblyVersion = "1.0.20140.46";
        internal const System.String AssemblyFileVersion = "1.0.20140.46";
        internal const System.Boolean ComVisible = false;
        internal const System.String Guid = "8B2765D7-A756-45AA-B7BD-4FB98F9F51F4";
        internal const System.String InternalsVisibleTo = "FiveChecks.Tests";
        internal const System.String NeutralResourcesLanguage = "en-US";
    }
}
