//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compliance.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compliance.Notifications.Resources.Resource.Strings", typeof(Resource_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String112 {
            get {
                return ResourceManager.GetString("_String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String113 {
            get {
                return ResourceManager.GetString("_String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String114 {
            get {
                return ResourceManager.GetString("_String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String115 {
            get {
                return ResourceManager.GetString("_String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String116 {
            get {
                return ResourceManager.GetString("_String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String117 {
            get {
                return ResourceManager.GetString("_String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String118 {
            get {
                return ResourceManager.GetString("_String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String119 {
            get {
                return ResourceManager.GetString("_String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String12 {
            get {
                return ResourceManager.GetString("_String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String120 {
            get {
                return ResourceManager.GetString("_String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String121 {
            get {
                return ResourceManager.GetString("_String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String122 {
            get {
                return ResourceManager.GetString("_String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String123 {
            get {
                return ResourceManager.GetString("_String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String13 {
            get {
                return ResourceManager.GetString("_String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String14 {
            get {
                return ResourceManager.GetString("_String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String15 {
            get {
                return ResourceManager.GetString("_String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String16 {
            get {
                return ResourceManager.GetString("_String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String17 {
            get {
                return ResourceManager.GetString("_String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String18 {
            get {
                return ResourceManager.GetString("_String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _String.
        /// </summary>
        internal static string _String19 {
            get {
                return ResourceManager.GetString("_String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must call RegisterActivator first..
        /// </summary>
        internal static string ActivatorRegistrationError {
            get {
                return ResourceManager.GetString("ActivatorRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must call RegisterAumidAndComServer first..
        /// </summary>
        internal static string AumidAndComRegistrationError {
            get {
                return ResourceManager.GetString("AumidAndComRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space is critically low. This have consequence for system stability, program installations and update of Windows..
        /// </summary>
        internal static string DiskSpaceIsLow_Description {
            get {
                return ResourceManager.GetString("DiskSpaceIsLow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space is low!.
        /// </summary>
        internal static string DiskSpaceIsLow_Title {
            get {
                return ResourceManager.GetString("DiskSpaceIsLow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an AUMID..
        /// </summary>
        internal static string MissingAumidError {
            get {
                return ResourceManager.GetString("MissingAumidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please cleanup at least {0:0.00} GB..
        /// </summary>
        internal static string Please_Cleanup_DiskSpace_Text_F0 {
            get {
                return ResourceManager.GetString("Please_Cleanup_DiskSpace_Text_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        internal static string ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value needs to be positive..
        /// </summary>
        internal static string ValueNeedsToBePositive {
            get {
                return ResourceManager.GetString("ValueNeedsToBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You activated the toast.
        /// </summary>
        internal static string YouActivatedTheToast {
            get {
                return ResourceManager.GetString("YouActivatedTheToast", resourceCulture);
            }
        }
    }
}
