//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compliance.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compliance.Notifications.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String101 {
            get {
                return ResourceManager.GetString("_String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String103 {
            get {
                return ResourceManager.GetString("_String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String105 {
            get {
                return ResourceManager.GetString("_String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String106 {
            get {
                return ResourceManager.GetString("_String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String107 {
            get {
                return ResourceManager.GetString("_String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _string.
        /// </summary>
        internal static string _String108 {
            get {
                return ResourceManager.GetString("_String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordMessageBoxCaption {
            get {
                return ResourceManager.GetString("ChangePasswordMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        internal static string DiskSpaceIsLow_ActionButton_Content {
            get {
                return ResourceManager.GetString("DiskSpaceIsLow_ActionButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low disk space may have consequence for system stability, program installations and update of Windows..
        /// </summary>
        internal static string DiskSpaceIsLow_Description {
            get {
                return ResourceManager.GetString("DiskSpaceIsLow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space is low!.
        /// </summary>
        internal static string DiskSpaceIsLow_Title {
            get {
                return ResourceManager.GetString("DiskSpaceIsLow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        internal static string GoodAfterNoon {
            get {
                return ResourceManager.GetString("GoodAfterNoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        internal static string NotNowActionButtonContent {
            get {
                return ResourceManager.GetString("NotNowActionButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string PasswordExpiryNotification_ActionButtonContent {
            get {
                return ResourceManager.GetString("PasswordExpiryNotification_ActionButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password expires in {0} on {1}. Please change your password before it expires..
        /// </summary>
        internal static string PasswordExpiryNotification_Content_F0_F1 {
            get {
                return ResourceManager.GetString("PasswordExpiryNotification_Content_F0_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to configure all your devices (PC, VDI, mobile phone, tablet) to use the new password..
        /// </summary>
        internal static string PasswordExpiryNotification_Content2 {
            get {
                return ResourceManager.GetString("PasswordExpiryNotification_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password expires soon!.
        /// </summary>
        internal static string PasswordExpiryNotification_Title {
            get {
                return ResourceManager.GetString("PasswordExpiryNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart....
        /// </summary>
        internal static string PendingRebootNotification_ActionButtonContent {
            get {
                return ResourceManager.GetString("PendingRebootNotification_ActionButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security and stability reasons, we kindly ask you to restart your computer as soon as possible..
        /// </summary>
        internal static string PendingRebootNotification_Content1 {
            get {
                return ResourceManager.GetString("PendingRebootNotification_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting your computer on a regular basis ensures a secure and stable Windows. Thank you in advance!.
        /// </summary>
        internal static string PendingRebootNotification_Content2 {
            get {
                return ResourceManager.GetString("PendingRebootNotification_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer needs a restart!.
        /// </summary>
        internal static string PendingRebootNotification_Title {
            get {
                return ResourceManager.GetString("PendingRebootNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please cleanup at least {0:0.00} GB..
        /// </summary>
        internal static string Please_Cleanup_DiskSpace_Text_F0 {
            get {
                return ResourceManager.GetString("Please_Cleanup_DiskSpace_Text_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl-Alt-Delete to change password..
        /// </summary>
        internal static string PressCtrlAltDeleteToGetToTheWindowsSecurityDialog {
            get {
                return ResourceManager.GetString("PressCtrlAltDeleteToGetToTheWindowsSecurityDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string SnoozeButtonContent {
            get {
                return ResourceManager.GetString("SnoozeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart....
        /// </summary>
        internal static string SystemUptime_Action_Button_Content {
            get {
                return ResourceManager.GetString("SystemUptime_Action_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to restart you computer..
        /// </summary>
        internal static string SystemUptime_Title {
            get {
                return ResourceManager.GetString("SystemUptime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer has been up for {0}..
        /// </summary>
        internal static string SystemUptimeContent_F0 {
            get {
                return ResourceManager.GetString("SystemUptimeContent_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting your computer on a regular basis ensures a secure and stable Windows. Thank you in advance!.
        /// </summary>
        internal static string SystemUptimeContent2 {
            get {
                return ResourceManager.GetString("SystemUptimeContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        internal static string ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value needs to be positive..
        /// </summary>
        internal static string ValueNeedsToBePositive {
            get {
                return ResourceManager.GetString("ValueNeedsToBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You activated the toast.
        /// </summary>
        internal static string YouActivatedTheToast {
            get {
                return ResourceManager.GetString("YouActivatedTheToast", resourceCulture);
            }
        }
    }
}
